package com.yalong.entity;
// Generated 2020-3-27 16:01:25 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EvaluateValve generated by hbm2java
 */
@Entity
@Table(name = "evaluate_valve", schema = "dbo", catalog = "EvaluationSystem")
public class EvaluateValve implements java.io.Serializable {

	private String id;
	private String VId;
	private String VName;
	private Date VTime;
	private String VSpeed;
	private String VCaliber;
	private String VLength;
	private String VExternalTemperature;
	private String VAmbientTemperature;
	private String VHeatLoss;
	private String VResult;

	public EvaluateValve() {
	}

	public EvaluateValve(String id) {
		this.id = id;
	}

	public EvaluateValve(String id, String VId, String VName, Date VTime, String VSpeed, String VCaliber,
			String VLength, String VExternalTemperature, String VAmbientTemperature, String VHeatLoss, String VResult) {
		this.id = id;
		this.VId = VId;
		this.VName = VName;
		this.VTime = VTime;
		this.VSpeed = VSpeed;
		this.VCaliber = VCaliber;
		this.VLength = VLength;
		this.VExternalTemperature = VExternalTemperature;
		this.VAmbientTemperature = VAmbientTemperature;
		this.VHeatLoss = VHeatLoss;
		this.VResult = VResult;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "vid", length = 30)
	public String getVId() {
		return VId;
	}

	public void setVId(String eId) {
		VId = eId;
	}

	@Column(name = "VName", length = 30)
	public String getVName() {
		return VName;
	}

	public void setVName(String eName) {
		VName = eName;
	}

	@Column(name = "VTime", length = 30)
	public Date getVTime() {
		return VTime;
	}

	public void setVTime(Date vTime) {
		this.VTime = vTime;
	}

	@Column(name = "VSpeed", length = 30)
	public String getVSpeed() {
		return VSpeed;
	}

	public void setVSpeed(String vSpeed) {
		this.VSpeed = vSpeed;
	}

	@Column(name = "VCaliber", length = 30)
	public String getVCaliber() {
		return VCaliber;
	}

	public void setVCaliber(String vCaliber) {
		this.VCaliber = vCaliber;
	}

	@Column(name = "VLength", length = 30)
	public String getVLength() {
		return VLength;
	}

	public void setVLength(String vLength) {
		this.VLength = vLength;
	}

	@Column(name = "VExternalTemperature", length = 30)
	public String getVExternalTemperature() {
		return VExternalTemperature;
	}

	public void setVExternalTemperature(String eExternalTemperature) {
		VExternalTemperature = eExternalTemperature;
	}

	@Column(name = "VAmbientTemperature", length = 30)
	public String getVAmbientTemperature() {
		return VAmbientTemperature;
	}

	public void setVAmbientTemperature(String eAmbientTemperature) {
		VAmbientTemperature = eAmbientTemperature;
	}

	@Column(name = "VHeatLoss", length = 30)

	public String getVHeatLoss() {
		return VHeatLoss;
	}

	public void setVHeatLoss(String vHeatLoss) {
		this.VHeatLoss = vHeatLoss;
	}

	@Column(name = "VResult", length = 30)
	public String getVResult() {
		return VResult;
	}

	public void setVResult(String vResult) {
		this.VResult = vResult;
	}

}
