package com.yalong.entity;
// Generated 2020-3-27 16:01:25 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EvaluatePipeline generated by hbm2java
 */
@Entity
@Table(name = "evaluate_pipeline", schema = "dbo", catalog = "EvaluationSystem")
public class EvaluatePipeline implements java.io.Serializable {

	private String id;
	private String PId;
	private String PName;
	private Date   PTime;
	private String PSpeed;
	private String PCaliber;
	private String PLength;
	private String PExternalTemperature;
	private String PAmbientTemperature;
	private String PHeatLoss;
	private String PResult;

	public EvaluatePipeline() {
	}

	public EvaluatePipeline(String id) {
		this.id = id;
	}

	public EvaluatePipeline(String id, String PId, String PName, Date PTime, String PSpeed, String PCaliber,
			String PLength, String PExternalTemperature, String PAmbientTemperature, String PHeatLoss, String PResult) {
		this.id = id;
		this.PId = PId;
		this.PName = PName;
		this.PTime = PTime;
		this.PSpeed = PSpeed;
		this.PCaliber = PCaliber;
		this.PLength = PLength;
		this.PExternalTemperature = PExternalTemperature;
		this.PAmbientTemperature = PAmbientTemperature;
		this.PHeatLoss = PHeatLoss;
		this.PResult = PResult;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "p_id", length = 30)
	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	@Column(name = "p_name", length = 30)
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@Column(name = "p_time", length = 30)
	public Date getPTime() {
		return this.PTime;
	}

	public void setPTime(Date PTime) {
		this.PTime = PTime;
	}

	@Column(name = "p_speed", length = 30)
	public String getPSpeed() {
		return this.PSpeed;
	}

	public void setPSpeed(String PSpeed) {
		this.PSpeed = PSpeed;
	}

	@Column(name = "p_caliber", length = 30)
	public String getPCaliber() {
		return this.PCaliber;
	}

	public void setPCaliber(String PCaliber) {
		this.PCaliber = PCaliber;
	}

	@Column(name = "p_length", length = 30)
	public String getPLength() {
		return this.PLength;
	}

	public void setPLength(String PLength) {
		this.PLength = PLength;
	}

	@Column(name = "p_external_temperature", length = 30)
	public String getPExternalTemperature() {
		return this.PExternalTemperature;
	}

	public void setPExternalTemperature(String PExternalTemperature) {
		this.PExternalTemperature = PExternalTemperature;
	}

	@Column(name = "p_ambient_temperature", length = 30)
	public String getPAmbientTemperature() {
		return this.PAmbientTemperature;
	}

	public void setPAmbientTemperature(String PAmbientTemperature) {
		this.PAmbientTemperature = PAmbientTemperature;
	}

	@Column(name = "p_heat_loss", length = 30)
	public String getPHeatLoss() {
		return this.PHeatLoss;
	}

	public void setPHeatLoss(String PHeatLoss) {
		this.PHeatLoss = PHeatLoss;
	}

	@Column(name = "p_result", length = 30)
	public String getPResult() {
		return this.PResult;
	}

	public void setPResult(String PResult) {
		this.PResult = PResult;
	}

}
