package com.yalong.entity;
// Generated 2020-3-27 16:01:25 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetadataElbow generated by hbm2java
 */
@Entity
@Table(name = "metadata_elbow", schema = "dbo", catalog = "EvaluationSystem")
public class MetadataElbow implements java.io.Serializable {

	private String EId;
	private String EType;
	private String EPressure;
	private String EFlow;
	private String ETemperature;
	private String ECaliber;
	private String EThickness;

	public MetadataElbow() {
	}

	public MetadataElbow(String EId) {
		this.EId = EId;
	}

	public MetadataElbow(String EId, String EType, String EPressure, String EFlow, String ETemperature, String ECaliber,
			String ELength, String EThickness, String eid, String etype, String epressure, String eflow,
			String etemperature, String ecaliber, String ethickness) {
		this.EId = EId;
		this.EType = EType;
		this.EPressure = EPressure;
		this.EFlow = EFlow;
		this.ETemperature = ETemperature;
		this.ECaliber = ECaliber;
		this.EThickness = EThickness;
	}

	@Id

	@Column(name = "e_id", unique = true, nullable = false, length = 30)
	public String getEId() {
		return this.EId;
	}

	public void setEId(String EId) {
		this.EId = EId;
	}

	@Column(name = "e_type", length = 30)
	public String getEType() {
		return this.EType;
	}

	public void setEType(String EType) {
		this.EType = EType;
	}

	@Column(name = "e_pressure", length = 30)
	public String getEPressure() {
		return this.EPressure;
	}

	public void setEPressure(String EPressure) {
		this.EPressure = EPressure;
	}

	@Column(name = "e_flow", length = 30)
	public String getEFlow() {
		return this.EFlow;
	}

	public void setEFlow(String EFlow) {
		this.EFlow = EFlow;
	}

	@Column(name = "e_temperature", length = 30)
	public String getETemperature() {
		return this.ETemperature;
	}

	public void setETemperature(String ETemperature) {
		this.ETemperature = ETemperature;
	}

	@Column(name = "e_caliber", length = 30)
	public String getECaliber() {
		return this.ECaliber;
	}

	public void setECaliber(String ECaliber) {
		this.ECaliber = ECaliber;
	}



	@Column(name = "e_thickness", length = 30)
	public String getEThickness() {
		return this.EThickness;
	}

	public void setEThickness(String EThickness) {
		this.EThickness = EThickness;
	}


}
