package com.yalong.entity;
// Generated 2020-3-27 16:01:25 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetadataPipeline generated by hbm2java
 */
@Entity
@Table(name = "metadata_pipeline", schema = "dbo", catalog = "EvaluationSystem")
public class MetadataPipeline implements java.io.Serializable {

	private String PId;
	private String PType;
	private String PPressure;
	private String PFlow;
	private String PTemperature;
	private String PCaliber;
	private String PLength;
	private String PThickness;

	public MetadataPipeline() {
	}

	public MetadataPipeline(String PId) {
		this.PId = PId;
	}

	public MetadataPipeline(String PId, String PType, String PPressure, String PFlow, String PTemperature,
			String PCaliber, String PLength, String PThickness) {
		this.PId = PId;
		this.PType = PType;
		this.PPressure = PPressure;
		this.PFlow = PFlow;
		this.PTemperature = PTemperature;
		this.PCaliber = PCaliber;
		this.PLength = PLength;
		this.PThickness = PThickness;
	}

	@Id

	@Column(name = "pid", unique = true, nullable = false, length = 30)
	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	@Column(name = "ptype", length = 30)
	public String getPType() {
		return this.PType;
	}

	public void setPType(String PType) {
		this.PType = PType;
	}

	@Column(name = "ppressure", length = 30)
	public String getPPressure() {
		return this.PPressure;
	}

	public void setPPressure(String PPressure) {
		this.PPressure = PPressure;
	}

	@Column(name = "pflow", length = 30)
	public String getPFlow() {
		return this.PFlow;
	}

	public void setPFlow(String PFlow) {
		this.PFlow = PFlow;
	}

	@Column(name = "ptemperature", length = 30)
	public String getPTemperature() {
		return this.PTemperature;
	}

	public void setPTemperature(String PTemperature) {
		this.PTemperature = PTemperature;
	}

	@Column(name = "pcaliber", length = 30)
	public String getPCaliber() {
		return this.PCaliber;
	}

	public void setPCaliber(String PCaliber) {
		this.PCaliber = PCaliber;
	}

	@Column(name = "plength", length = 30)
	public String getPLength() {
		return this.PLength;
	}

	public void setPLength(String PLength) {
		this.PLength = PLength;
	}

	@Column(name = "pthickness", length = 30)
	public String getPThickness() {
		return this.PThickness;
	}

	public void setPThickness(String PThickness) {
		this.PThickness = PThickness;
	}

}
