package com.yalong.entity;
// Generated 2020-3-26 11:06:07 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "_user", schema = "dbo", catalog = "EvaluationSystem")
public class User implements java.io.Serializable {

	private String id;
	private String name;
	private String password;
	private String role;
	private String gender;
	private String position;
	private String phone;
	private String age;
	public User() {
	}

	public User(String id, String name, String password, String role,String gender,String position,String age,String phone) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.role = role;
		this.age=age;
		this.gender=gender;
		this.phone=phone;
		this.position=position;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role", nullable = false, length = 10)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	@Column(name = "gender", nullable = false, length = 30)
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
	@Column(name = "position", nullable = false, length = 30)
	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
	@Column(name = "phone", nullable = false, length = 30)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@Column(name = "age", nullable = false, length = 30)
	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

}
